# æ•°æ®åº“è¿æ¥è®¾ç½®
database:
  host: "127.0.0.1"
  port: 3306
  database: "steward_activity"
  username: "root"
  password: "root"
  extra-params: "?useUnicode=true&characterEncoding=utf8"

# go-cqhttpè®¾ç½®
go-cqhttp:
  # velocity ID
  proxy-id: "0"
  # æœåŠ¡å™¨åç§°æ˜ å°„
  server-name-mappings:
    oldtimes: "ğŸ•°ï¸æ—§æ—¶å…‰ä¿±ä¹éƒ¨"
    mousse: "ğŸ°æ…•æ–¯å°é•‡"
  # æœºå™¨äººHTTP APIåœ°å€
  url: "http://127.0.0.1:12345"
  groups:
    # ç”¨äºå‘é€æ—¥å¿—å’Œè¯¦ç»†æŠ¥å‘Šçš„ç¾¤
    log-group-id: 111111111
    # ç©å®¶ç¤¾ç¾¤
    community-group-id: 222222222
  reports:
    # æ˜¯å¦å°†æ—¥æŠ¥/æœˆæŠ¥ä¹Ÿå‘é€åˆ°ç©å®¶ç¤¾ç¾¤
    send-to-community-group: true